export const GameEvents = {
    NEW_LEVEL: "NEW_LEVEL",
    LEVEL_WIN: "LEVEL_WIN",
    LEVEL_LOSE: "LEVEL_LOSE",
    TOGGLE_VIDEO: "TOGGLE_VIDEO",
    GRID_FACE_ADVANCED: "GRID_FACE_ADVANCED",
    RELEASE_SHOOTER: "RELEASE_SHOOTER"
}